version: "3.9"
services:
  harbour-master1:
    image: solentdevops/harbour-master:0.1-SNAPSHOT
    ports:
      - "8080:8080"
    volumes:
      - order-example1-logs:/usr/local/tomcat/logs

  harbour-master2:
    image:  solentdevops/harbour-master:0.1-SNAPSHOT
    ports:
      - "8081:8080"
    volumes:
      - order-example2-logs:/usr/local/tomcat/logs


volumes:
  harbour-master1-logs: {}
  harbour-master2-logs: {}
