/*
 * Smart Port API
 * Solent university devops https://github.com/com619-2021
 *
 * OpenAPI spec version: v1
 * Contact: craig.gallen@solent.ac.uk
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package solent.ac.uk.devops.traffic.client.swagger.api;

import solent.ac.uk.devops.traffic.client.swagger.invoker.ApiException;
import org.solent.com504.project.model.dto.ReplyMessage;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for UserManagementApiApi
 */
@Ignore
public class UserManagementApiApiTest {

    private final UserManagementApiApi api = new UserManagementApiApi();

    /**
     * Create New User
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createUserTest() throws ApiException {
        String name = null;
        String password = null;
        ReplyMessage response = api.createUser(name, password);

        // TODO: test validations
    }
    /**
     * Find user by username
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getUserTest() throws ApiException {
        String username = null;
        ReplyMessage response = api.getUser(username);

        // TODO: test validations
    }
    /**
     * Find list of users
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getUsersTest() throws ApiException {
        ReplyMessage response = api.getUsers();

        // TODO: test validations
    }
    /**
     * all this does is ask for a text &#x27;hello world&#x27; response
     *
     * Returns text hello world
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void message1Test() throws ApiException {
        String response = api.message1();

        // TODO: test validations
    }
}
