/*
 * Smart Port API
 * Solent university devops https://github.com/com619-2021
 *
 * OpenAPI spec version: v1
 * Contact: craig.gallen@solent.ac.uk
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package solent.ac.uk.devops.traffic.client.swagger.api;

import solent.ac.uk.devops.traffic.client.swagger.invoker.ApiException;
import org.solent.com504.project.model.order.dto.Order;
import org.solent.com504.project.model.dto.ReplyMessage;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for OrderorderApi
 */
@Ignore
public class OrderorderApiTest {

    private final OrderorderApi api = new OrderorderApi();

    /**
     * Delete order by uuid
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteOrderByUuidTest() throws ApiException {
        String uuid = null;
        ReplyMessage response = api.deleteOrderByUuid(uuid);

        // TODO: test validations
    }
    /**
     * Find order by resource template
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getOrderTest() throws ApiException {
        Integer offset = null;
        Integer limit = null;
        ReplyMessage response = api.getOrder(offset, limit);

        // TODO: test validations
    }
    /**
     * Find order by order template (Should be GET but get with resources not allowed in swagger UI)
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getOrderByTemplateTest() throws ApiException {
        Order body = null;
        Integer offset = null;
        Integer limit = null;
        ReplyMessage response = api.getOrderByTemplate(body, offset, limit);

        // TODO: test validations
    }
    /**
     * Find order by uuid
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getOrderByuuidTest() throws ApiException {
        String uuid = null;
        ReplyMessage response = api.getOrderByuuid(uuid);

        // TODO: test validations
    }
    /**
     * Create new Order resource
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void postCreateOrderTest() throws ApiException {
        Order body = null;
        ReplyMessage response = api.postCreateOrder(body);

        // TODO: test validations
    }
    /**
     * update  Order resource
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void putUpdateOrderTest() throws ApiException {
        Order body = null;
        ReplyMessage response = api.putUpdateOrder(body);

        // TODO: test validations
    }
}
