/*
 * Smart Port API
 * Solent university devops https://github.com/com619-2021
 *
 * OpenAPI spec version: v1
 * Contact: craig.gallen@solent.ac.uk
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package solent.ac.uk.devops.traffic.client.swagger.api;

import solent.ac.uk.devops.traffic.client.swagger.invoker.ApiException;
import org.solent.com504.project.model.order.dto.Order;
import org.solent.com504.project.model.order.dto.OrderChangeRequest;
import org.solent.com504.project.model.dto.ReplyMessage;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for OrderorderChangeRequestApi
 */
@Ignore
public class OrderorderChangeRequestApiTest {

    private final OrderorderChangeRequestApi api = new OrderorderChangeRequestApi();

    /**
     * Delete orderChangeRequest by uuid
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteOrderChangeRequestByUuidTest() throws ApiException {
        String uuid = null;
        ReplyMessage response = api.deleteOrderChangeRequestByUuid(uuid);

        // TODO: test validations
    }
    /**
     * Find orderChangeRequest by resource template
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getOrderChangeRequestTest() throws ApiException {
        Integer offset = null;
        Integer limit = null;
        ReplyMessage response = api.getOrderChangeRequest(offset, limit);

        // TODO: test validations
    }
    /**
     * Find orderChangeRequest by resource template (Should be GET but get with resources not allowed in swagger UI)
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getOrderChangeRequestByTemplateTest() throws ApiException {
        Order body = null;
        Integer offset = null;
        Integer limit = null;
        ReplyMessage response = api.getOrderChangeRequestByTemplate(body, offset, limit);

        // TODO: test validations
    }
    /**
     * Find orderChangeRequest by uuid
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getOrderChangeRequestByuuidTest() throws ApiException {
        String uuid = null;
        ReplyMessage response = api.getOrderChangeRequestByuuid(uuid);

        // TODO: test validations
    }
    /**
     * Create new Order resource
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void postCreateOrderChangeRequestTest() throws ApiException {
        OrderChangeRequest body = null;
        ReplyMessage response = api.postCreateOrderChangeRequest(body);

        // TODO: test validations
    }
    /**
     * update  Order resource
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void putUpdateOrderChangeRequestTest() throws ApiException {
        OrderChangeRequest body = null;
        ReplyMessage response = api.putUpdateOrderChangeRequest(body);

        // TODO: test validations
    }
}
