/*
 * Smart Port API
 * Solent university devops https://github.com/com619-2021
 *
 * OpenAPI spec version: v1
 * Contact: craig.gallen@solent.ac.uk
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package solent.ac.uk.devops.traffic.client.swagger.api;

import solent.ac.uk.devops.traffic.client.swagger.invoker.ApiException;
import org.solent.com504.project.model.dto.ReplyMessage;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ServicetestApi
 */
@Ignore
public class ServicetestApiTest {

    private final ServicetestApi api = new ServicetestApi();

    /**
     * This is simply a test method to check there is a heartbeat reply message
     *
     * simply returns an incrimenting heartbeat in debug message
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getHeartbeatTest() throws ApiException {
        ReplyMessage response = api.getHeartbeat();

        // TODO: test validations
    }
    /**
     * all this does is ask for a text &#x27;hello world&#x27; response
     *
     * Returns text hello world
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void messageTest() throws ApiException {
        String response = api.message();

        // TODO: test validations
    }
}
