/*
 * Smart Port API
 * Solent university devops https://github.com/com619-2021
 *
 * OpenAPI spec version: v1
 * Contact: craig.gallen@solent.ac.uk
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package solent.ac.uk.devops.traffic.client.swagger.api;

import solent.ac.uk.devops.traffic.client.swagger.invoker.ApiException;
import org.solent.com504.project.model.dto.ReplyMessage;
import org.solent.com504.project.model.resource.dto.Resource;
import org.solent.com504.project.model.resource.dto.ResourceCatalog;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ResourcecatalogApi
 */
@Ignore
public class ResourcecatalogApiTest {

    private final ResourcecatalogApi api = new ResourcecatalogApi();

    /**
     * Delete catalog resource by uuid
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteResourceCatalogByUuidTest() throws ApiException {
        String uuid = null;
        ReplyMessage response = api.deleteResourceCatalogByUuid(uuid);

        // TODO: test validations
    }
    /**
     * Find catalog resource by resource template
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getResourceCatalogTest() throws ApiException {
        Integer offset = null;
        Integer limit = null;
        ReplyMessage response = api.getResourceCatalog(offset, limit);

        // TODO: test validations
    }
    /**
     * Find catalog resource by resource template (Should be GET but get with resources not allowed in swagger UI)
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getResourceCatalogByTemplateTest() throws ApiException {
        ResourceCatalog body = null;
        Integer offset = null;
        Integer limit = null;
        ReplyMessage response = api.getResourceCatalogByTemplate(body, offset, limit);

        // TODO: test validations
    }
    /**
     * Find catalog resource by uuid
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getResourceCatalogByuuidTest() throws ApiException {
        String uuid = null;
        ReplyMessage response = api.getResourceCatalogByuuid(uuid);

        // TODO: test validations
    }
    /**
     * Create new Catalog resource
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void postCreateResourceCatalogTest() throws ApiException {
        Resource body = null;
        ReplyMessage response = api.postCreateResourceCatalog(body);

        // TODO: test validations
    }
    /**
     * update  Catalog resource
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void putUpdateResourceCatalogTest() throws ApiException {
        Resource body = null;
        ReplyMessage response = api.putUpdateResourceCatalog(body);

        // TODO: test validations
    }
}
