name: Test-Workflow

on:
  release:
    types: [published]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Get Release Tag
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          
      - name: 'Login to docker with GHCR'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Build with Maven
        working-directory: ./experimental/HarbourMaster/harbour-master/
        run: | 
          mvn -B -X --update-snapshots clean package -P packageAsDocker
          docker build ./docker -f ./docker/Dockerfile -t ghcr.io/${{ github.repository_owner }}/harbour:${{ env.RELEASE_VERSION }}
          docker push ghcr.io/${{ github.repository_owner }}/harbour:${{ env.RELEASE_VERSION }}
          
          
      - name: Upload artifact
        uses: actions/upload-artifact@v1
        with:
          name: surefire-reports
          path: ./experimental/HarbourMaster/harbour-master/dao/target/surefire-reports/**
          
      - name: Send dispatch to Repository
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.PAT }}
          repository: com619-2021/IntegrationA 
          event-type: deploy
          client-payload: '{"image_owner": "HARBOUR_IMAGE" ,"image_tag": "ghcr.io/${{ github.repository_owner }}/harbour:${{ env.RELEASE_VERSION }}"}'
